### ISSUE TITLE
Bundles are not working properly on FreeBSD 12.2

### ISSUE THREAD

**Issue by gcasa** [gnustep/tools-make#10]
A recent issue was discussed on the list regarding -r and -rdynamic.   A suggestion was made to remove -rdynamic from the subproject.  The issue with doing this is that this impacts bundles being loaded.  In 1998, RFM made a change to add -rdynamic to "Allow bundles to work properly" and until recently this worked just fine on FreeBSD.

Steps to reproduce this are:
1) download and GNUstep on FreeBSD
2) modify target.make to remove -rdynamic from ADDITIONAL_LDFLAGS
3) build GNUstep and install
4) build Gorm
5) run Gorm

Current result: Bundles and shared libraries refuse to load
Expected: Bundles and shared libraries should load.

Now... this change could be more specific, but it leads me to conclude that if this change were applied to bundles that they too would not load properly.  So, I believe the issue is with the linker used.  Currently mine is set to use ld.lld.

**Comment by fredkiefer** [comment]
I did unassign myself from this ticket as I am the one GNUstep developer not using clang. With my setup I am not even able to reproduce this issue, how should I fix it?

**Comment by davidchisnall** [comment]
I find the -make infrastructure incredibly confusing and so cannot fix this.  I believe the fix is one of:

 - Move `-rdynamic` or `--export-dynamic` from the general `LDFLAGS` into a separate `FINAL_LINK_FLAGS` and add that to the target's linker flags only for things that generate loadable binaries (programs, shared libraries).
 - Explicitly remove `-rdynamic` and `--export-dynamic` from the flags passed to the linker from partial links.

The suggestion to remove `-rdynamic` was due to the incompatibility between `-r` (partial link, create a relocatable object) and `-rdynamic` (put all symbols on the dynamic symbol table, which makes sense only for final links).  With some linkers, this combination of flags causes `--export-dynamic` to be silently ignored, with others it causes an error (don't put flags that only affect a final link in the linker invocation for a partial link).  

Your change appears to have removed `-rdynamic` from the flags entirely, which is likely to break things.

**Comment by gcasa** [comment]
> I find the -make infrastructure incredibly confusing and so cannot fix this. I believe the fix is one of:
> 
> * Move `-rdynamic` or `--export-dynamic` from the general `LDFLAGS` into a separate `FINAL_LINK_FLAGS` and add that to the target's linker flags only for things that generate loadable binaries (programs, shared libraries).
> * Explicitly remove `-rdynamic` and `--export-dynamic` from the flags passed to the linker from partial links.
> 
> The suggestion to remove `-rdynamic` was due to the incompatibility between `-r` (partial link, create a relocatable object) and `-rdynamic` (put all symbols on the dynamic symbol table, which makes sense only for final links). With some linkers, this combination of flags causes `--export-dynamic` to be silently ignored, with others it causes an error (don't put flags that only affect a final link in the linker invocation for a partial link).
> 
> Your change appears to have removed `-rdynamic` from the flags entirely, which is likely to break things.

It did.  The initial issue was not being able to link libs-back and getting an error regarding -r and --export-dynamic.  For some reason this has recently broken.   I probably should have written an issue on that.  I believe the best person to fix this is @rfm.

**Comment by rfm** [comment]
I'm not sure why I'm expected to know about linker flags (I don't), and I have never used FreeBSD and don't have a FreeBSD system.
However, if I understand David's comment correctly, there are some systems (presumably FreeBSD) where -rdynamic is incompatible with -r for some links, -rdynamic is needed for 'full' links and -r for 'partial; links.
I don't know what count as full and what count as partial links though.  Is it the case that only subprojects count as 'partial'; links?  If so the suggestion of removing -rdynamic from subprojects seems the easy option.

**Comment by rfm** [comment]
Looking at gnustep-make, it seemed to be fairly simple/clean to have a new 'final' flags variable, so I comitted a change to do that.  Please can someone who uses systems where the problem exists give it a try.

**Comment by davidchisnall** [comment]
Any system using the latest LLD to link will hit this issue.

**Comment by gcasa** [comment]
I just updated.  A fix has been made that solves the root issue here.
